@startuml

title __DHBWORLD's Class Diagram__\n

  namespace com.main.dhbworld {
    class com.main.dhbworld.MainActivity {
        # onCreate()
    }
  }
  

  namespace com.main.dhbworld {
    class com.main.dhbworld.UserInteraction {
        - imageBox_drucker : LinearLayout
        - imageBox_kaffee : LinearLayout
        - imageBox_kantine : LinearLayout
        - ja : ArrayList<Button>
        - meldungenDruker : int
        - meldungenDrukerTV : TextView
        - meldungenKaffee : int
        - meldungenKaffeeTV : TextView
        - meldungenKantine : int
        - meldungenKantineTV : TextView
        - nein : ArrayList<Button>
        - zustandDrukerTV : TextView
        - zustandKaffeeTV : TextView
        - zustandKantineTV : TextView
        + getMeldungenDruker()
        + getMeldungenKaffee()
        + getMeldungenKantine()
        + getZustandDruker()
        + getZustandKaffee()
        + getZustandKantine()
        + setMeldungenDruker()
        + setMeldungenKaffee()
        + setMeldungenKantine()
        + setZustandDruker()
        + setZustandKaffee()
        + setZustandKantine()
        # onCreate()
        - jaNeinButtonsManagement()
        - meldungenManagement()
        - updateInteractionState()
        - zustandManagement()
    }
  }

   namespace com.main.dhbworld {
      namespace Firebase {
        interface com.main.dhbworld.Firebase.CurrentStatusListener {
            {abstract} + onStatusReceived()
        }
      }
    }


    namespace com.main.dhbworld {
      namespace Firebase {
        interface com.main.dhbworld.Firebase.DataSendListener {
            {abstract} + failed()
            {abstract} + success()
        }
      }
    }


    namespace com.main.dhbworld {
      namespace Firebase {
        class com.main.dhbworld.Firebase.Issue {
            - problem : int
            - timestamp : long
            + getProblem()
            + getTimestamp()
            + setProblem()
            + setTimestamp()
            + toString()
            ~ Issue()
            ~ Issue()
        }
      }
    }


    namespace com.main.dhbworld {
      namespace Firebase {
        interface com.main.dhbworld.Firebase.SignedInListener {
            {abstract} + onSignInError()
            {abstract} + onSignedIn()
        }
      }
    }


    namespace com.main.dhbworld {
      namespace Firebase {
        class com.main.dhbworld.Firebase.TooManyClicksException {
            + TooManyClicksException()
        }
      }
    }


    namespace com.main.dhbworld {
      namespace Firebase {
        class com.main.dhbworld.Firebase.Utilities {
            {static} + CATEGORY_CAFETERIA : String
            {static} + CATEGORY_COFFEE : String
            {static} + CATEGORY_PRINTER : String
            - database : FirebaseDatabase
            - editor : Editor
            {static} - emulatorIp : String
            {static} - invalidateTime : long
            {static} - invalidateTimeClicks : long
            {static} - invalidateTimeSwitch : long
            - lastClick : long
            - mAuth : FirebaseAuth
            - preferences : SharedPreferences
            - user : FirebaseUser
            + Utilities()
            + addToDatabase()
            + getCurrentStatus()
            + getUser()
            + removeFromDatabase()
            + setCurrentStatusListener()
            + setDataSendListener()
            + setSignedInListener()
            + signIn()
            {static} + subscribeToTopic()
            - getIssueDatabase()
            - getIssueDatabase()
            - getIssueDatabaseWithUser()
        }
      }
    }

    namespace com.main.dhbworld {
      namespace Services {
        class com.main.dhbworld.Services.UserInteractionMessagingService {
            + handleIntent()
            + onMessageReceived()
            + onNewToken()
            - createNotificationChannel()
        }
      }
    }

    namespace com.main.dhbworld {
      namespace Fragments {
        class com.main.dhbworld.Fragments.DialogCofirmationUserInteraction {
            - nameOfSelectedState : String
            + DialogCofirmationUserInteraction()
            + DialogCofirmationUserInteraction()
            + getNameOfSelectedState()
            + getSelectedState()
        }
      }
    }

    namespace com.main.dhbworld {
      namespace Enums {
        enum InteractionState {
          CLEANING
          DEFECT
          NORMAL
          QUEUE_ABCENT
          QUEUE_KURZ
          QUEUE_LONG
          QUEUE_MIDDLE
          color
          id
          text
        }
      }
    }

    namespace com.main.dhbworld {
      namespace BroadcastReceiver {
        class com.main.dhbworld.BroadcastReceiver.UpdateEventsReceiver {
            + onReceive()
            {static} + setReceiver()
        }
      }
    }


    com.main.dhbworld.BroadcastReceiver.UpdateEventsReceiver -up-|> android.content.BroadcastReceiver


    com.main.dhbworld.Fragments.DialogCofirmationUserInteraction -up-|> com.google.android.material.dialog.MaterialAlertDialogBuilder
    com.main.dhbworld.Fragments.DialogCofirmationUserInteraction o-- com.main.dhbworld.Enums.InteractionState : selectedState
    com.main.dhbworld.Services.UserInteractionMessagingService -up-|> com.google.firebase.messaging.FirebaseMessagingService
    com.main.dhbworld.Firebase.Utilities o-- com.main.dhbworld.Firebase.CurrentStatusListener : currentStatusListener
    com.main.dhbworld.Firebase.Utilities o-- com.main.dhbworld.Firebase.DataSendListener : dataSendListener
    com.main.dhbworld.Firebase.Utilities o-- com.main.dhbworld.Firebase.SignedInListener : signedInListener
    com.main.dhbworld.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
    com.main.dhbworld.UserInteraction -up-|> androidx.appcompat.app.AppCompatActivity
    com.main.dhbworld.UserInteraction o-- com.main.dhbworld.Firebase.Utilities : firebaseUtilities
    com.main.dhbworld.UserInteraction o-- com.main.dhbworld.Enums.InteractionState : zustandDruker
    com.main.dhbworld.UserInteraction o-- com.main.dhbworld.Enums.InteractionState : zustandKaffee
    com.main.dhbworld.UserInteraction o-- com.main.dhbworld.Enums.InteractionState : zustandKantine


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
