@startuml

title __KVV class diagram__\n

  namespace com.main.dhbworld.KVV {
    class com.main.dhbworld.KVV.KVVActivity {
        ~ departures : ArrayList<Departure>
        ~ localDateTime : LocalDateTime
        ~ progressIndicator : CircularProgressIndicator
        ~ recyclerView : RecyclerView
        ~ refreshButton : MaterialButton
        ~ textViewDepartureDateSelect : TextView
        ~ textViewDepartureTimeSelect : TextView
        ~ tramDepartureDateSelectCardView : MaterialCardView
        ~ tramDepartureTimeSelectCardView : MaterialCardView
        ~ tramDisruptionCardView : MaterialCardView
        ~ tramDisruptionTitle : TextView
        + onDataLoaded()
        # onCreate()
        - dateSelectClick()
        - initViews()
        - refresh()
        - setupAdapter()
        - setupClickListeners()
        - setupTextViews()
        - timeSelectClick()
    }

    note left : Uses ArrayList of Departues\ninstead of just one departure object

  }
      namespace com.main.dhbworld.KVV {
        class com.main.dhbworld.KVV.Departure {
            - attribute : String
            - departureTime : LocalDateTime
            - destination : String
            - line : String
            - notServiced : boolean
            - platform : String
            + Departure()
            + getAttribute()
            + getDepartureTime()
            + getDestination()
            + getLine()
            + getPlatform()
            + isNotServiced()
            + setAttribute()
            + setDepartureTime()
            + setDestination()
            + setLine()
            + setNotServiced()
            + setPlatform()
            + toString()
        }
      }

    com.main.dhbworld.KVV.KVVActivity o-> com.main.dhbworld.KVV.Departure


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
