name: Android CI
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Android  Report Action
      uses: doanpt/AndroidTestReportAction@v1.1
      
      
    #- name: Instrumentation Tests
    #  uses: reactivecircus/android-emulator-runner@v2
    #  with:
    #    api-level: 27
    #    arch: x86_64
    #    script: ./gradlew connectedAndroidTest
    #  continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step
    
      # Set up platform tools like adb.
    - run: sdkmanager platform-tools

    # Start ADB (and verify that pathing is working correctly).
    - run: adb devices

    # Verify $ANDROID_HOME is properly set for later Gradle commands.
    - run: echo $ANDROID_HOME
    
    - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
      with:
        cmd: ./gradlew connectedAndroidTest
        api: 27
        tag: default
        abi: x86_64
        
    - name: Upload Test Reports Folder
      uses: actions/upload-artifact@v2
      if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
      with:
        name: reports
        path: app/build/reports/androidTests/connected/ # path to where the xml test results are stored

  ##5
  report:
    runs-on: [ self-hosted ]
    needs: build # The report job will run after test job
    if: ${{ always() }} # IMPORTANT: Execute report job regardless of status
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: reports
      - name: Android  Report Action
        uses: doanpt/AndroidTestReportAction@v1.1
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless


      
      
      
    
