name: Android Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Android  Report Action
      uses: doanpt/AndroidTestReportAction@v1.1
    
    - uses: blitzdose/action-android/install-sdk@release/0.1.4
      # Set up platform tools like adb.
    - run: sdkmanager platform-tools

    # Start ADB (and verify that pathing is working correctly).
    - run: adb devices

    # Verify $ANDROID_HOME is properly set for later Gradle commands.
    - run: echo $ANDROID_HOME
    
    - uses: blitzdose/action-android/emulator-run-cmd@release/0.1.4
      with:
        cmd: ./gradlew jacocoCombinedTestReports
        api: 27
        tag: default
        abi: x86_64
        cmdOptions: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
        
    - name: Upload Test Reports Folder
      uses: actions/upload-artifact@v2
      if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
      with:
        name: reports
        path: app/build/reports/androidTests/connected/ # path to where the xml test results are stored

  ##5
  report:
    runs-on: [ self-hosted ]
    needs: build # The report job will run after test job
    if: ${{ always() }} # IMPORTANT: Execute report job regardless of status
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: reports
      - name: Android  Report Action
        uses: doanpt/AndroidTestReportAction@v1.1
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
